name: Generate Snake Game

on:
  schedule:
    # Runs every day at midnight
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Generate the snake gif using Platane's snk action
      - name: Generate Snake Game
        uses: Platane/snk@v2
        with:
          github_user_name: YOUR_USERNAME # Replace with your GitHub username
          gif_out_path: dist/snake.gif

      # Step 3: Upload the snake gif as an artifact
      - name: Upload Snake GIF
        uses: actions/upload-artifact@v3
        with:
          name: snake-game
          path: dist/snake.gif
