name: Snake Game

on:
  push:
    branches:
      - main

jobs:
  snake-game:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Play Snake Game
        uses: Platane/snk@master
        with:
          github_user: VoudourisAm  # Your GitHub username is VoudourisAm
          svg: true

      - name: Commit snake.svg
        run: |
          mv snake.svg .github/images/snake.svg  # Move to a public folder
          git add .github/images/snake.svg
          git commit -m "Add snake game image"
          git push
