name: Snake Game

on:
  push:
    branches:
      - main

jobs:
  snake-game:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Play Snake Game
        uses: Platane/snk@master
        with:
          github_user: VoudourisAM
          svg: true
